### ISSUE TITLE
作者，apk地址不见了，能否给个下载链接

### ISSUE THREAD

**Issue by IOCloudFly** [JD-CP/flutter_eyepetizer#3]

**Comment by JD-CP** [comment]
目前蒲公英正在升级维护，导致二维码无法扫描下载。你可以clone到本地，run到你的手机，查看运行效果。

**Comment by IOCloudFly** [comment]
> 目前蒲公英正在升级维护，导致二维码无法扫描下载。你可以clone到本地，run到你的手机，查看运行效果。

项目clone到本地，可能是环境的原因，跑不起来，你还是放一个apk吧，打包一个直接放在github上面就行

**Comment by IOCloudFly** [comment]
> > 目前蒲公英正在升级维护，导致二维码无法扫描下载。你可以clone到本地，run到你的手机，查看运行效果。
> 
> 项目clone到本地，可能是环境的原因，跑不起来，你还是放一个apk吧，打包一个直接放在github上面就行

大佬，我问下，视频是不是在模拟器上无法播放，必须上真机才行

**Comment by IOCloudFly** [comment]
> > > 目前蒲公英正在升级维护，导致二维码无法扫描下载。你可以clone到本地，run到你的手机，查看运行效果。
> > 
> > 
> > 项目clone到本地，可能是环境的原因，跑不起来，你还是放一个apk吧，打包一个直接放在github上面就行
> 
> 大佬，我问下，视频是不是在模拟器上无法播放，必须上真机才行

>已经好了，ios虚拟机的确不行，效果挺不错的，厉害。

**Comment by JD-CP** [comment]
目前项目处于持续更新状态，您也可以保持持续关注，感谢支持🙏。

**Comment by IOCloudFly** [comment]
> 目前项目处于持续更新状态，�您也可以保持持续关注，感谢支持🙏。

大佬，方便给个微信吗？我有问题问题要问你
