### ISSUE TITLE
作者，我用每日推荐的接口，返回403

### ISSUE THREAD

**Issue by IOCloudFly** [JD-CP/flutter_eyepetizer#6]
如果浏览器里面可以直接访问，我用dio，给我返回403
接口地址是：http://baobab.kaiyanapp.com/api/v2/feed?num=1

我想请教一下，你是如何解决这个的。

**Comment by IOCloudFly** [comment]
作者，能否告诉一下，正确的接口地址是什么或者需要设置一下什么东西吗

**Comment by JD-CP** [comment]
不好意思，最近几天一直在忙。你可以仔细看一下我的项目代码，应该是某个地方没有配置。

**Comment by IOCloudFly** [comment]
> 不好意思，最近几天一直在忙。你可以仔细看一下我的项目代码，应该是某个地方没有配置。

大佬，能否帮忙看下代码，我是基本看你写的，数据加载不出来

**Comment by IOCloudFly** [comment]
> > 不好意思，最近几天一直在忙。你可以仔细看一下我的项目代码，应该是某个地方没有配置。
> 
> 大佬，能否帮忙看下代码，我是基本看你写的，数据加载不出来

https://github.com/IOCloudFly/flutter_phoenix/tree/fly，没有数据，也没有报错信息。

**Comment by JD-CP** [comment]
android/app/src/main/AndroidManifest.xml ，在配置文件里，加上网络请求权限 <uses-permission android:name="android.permission.INTERNET"/> 。

**Comment by IOCloudFly** [comment]
> android/app/src/main/AndroidManifest.xml ，在配置文件里，加上网络请求权限 。

不对吧，我里面还有其他接口都不需要网络请求权限都可以请求到数据，再说了我用的是苹果的模拟器，。。。。。。。。。。
