### ISSUE TITLE
大佬，请求帮个忙！！！！！

### ISSUE THREAD

**Issue by IOCloudFly** [JD-CP/flutter_eyepetizer#7]
在首页的列表的信息，我所有的都是仿照你写的，就是加载不出来数据，我的实体类是直接copy你的，也没有报错，debug也跟不出来，我用的是ios模拟器，而且我加上的了网络请求，Android也没有数据的，能否远程一下看下代码，看缺少什么，就那一点点代码，真的头大，我找了很多人，花了一百多都没解决。你出个价行吧，QQ :1147235807

**Comment by JD-CP** [comment]
加我微信吧，YGD220
